import { writeFileSync } from 'node:fs';
import type { CameraCfg } from '@yonderrc/protocol';

/**
 * Turns the graphical camera list into a go2rtc.yaml and reloads go2rtc — so the
 * user configures cameras (type, resolution, fps, bitrate) in the setup UI, not
 * by hand-editing a config file. Each camera becomes one selectable stream.
 */

function bitrateArgs(kbps?: number): string {
  return kbps && kbps > 0 ? ` -b:v ${kbps}k -maxrate ${kbps}k -bufsize ${kbps * 2}k` : '';
}

/** Build the go2rtc source string for one camera. */
export function cameraSource(cam: CameraCfg): string {
  const { width: w, height: h, fps } = cam;
  if (cam.type === 'sim') {
    return (
      `exec:ffmpeg -re -f lavfi -i testsrc=size=${w}x${h}:rate=${fps} ` +
      `-c:v libx264 -preset ultrafast -tune zerolatency -pix_fmt yuv420p -g ${fps}` +
      `${bitrateArgs(cam.bitrateKbps)} -f rtsp {output}`
    );
  }
  if (cam.type === 'rpicam') {
    const br = cam.bitrateKbps ? ` --bitrate ${cam.bitrateKbps * 1000}` : '';
    return (
      `exec:libcamera-vid -t 0 --inline --nopreview --codec h264 ` +
      `--width ${w} --height ${h} --framerate ${fps} --intra ${fps}${br} -o - | ` +
      `ffmpeg -fflags nobuffer -i - -c copy -f rtsp {output}`
    );
  }
  // usb (V4L2): transcode to H.264 with low latency.
  const dev = cam.device ?? '/dev/video0';
  return (
    `exec:ffmpeg -f v4l2 -framerate ${fps} -video_size ${w}x${h} -i ${dev} ` +
    `-c:v libx264 -preset ultrafast -tune zerolatency -pix_fmt yuv420p -g ${fps}` +
    `${bitrateArgs(cam.bitrateKbps)} -f rtsp {output}`
  );
}

export function generateGo2rtcYaml(cameras: CameraCfg[]): string {
  const lines: string[] = [
    '# Generated by YonderRC from the graphical camera settings — do not edit by hand.',
    'api:',
    '  listen: ":1984"',
    '  origin: "*"',
    'rtsp:',
    '  listen: ":8554"',
    'webrtc:',
    '  listen: ":8555"',
    '  candidates:',
    '    - stun:8555',
    'streams:',
  ];
  if (cameras.length === 0) {
    lines.push('  {}');
  } else {
    for (const cam of cameras) {
      // Quote the source so ffmpeg pipes/special chars survive YAML parsing.
      lines.push(`  ${cam.name}: ${JSON.stringify(cameraSource(cam))}`);
    }
  }
  return lines.join('\n') + '\n';
}

/** Write the config file and ask a running go2rtc to reload it. */
export async function applyCameras(
  cameras: CameraCfg[],
  configPath: string,
  videoBaseUrl: string | null,
): Promise<void> {
  writeFileSync(configPath, generateGo2rtcYaml(cameras));
  if (!videoBaseUrl) return;
  try {
    await fetch(`${videoBaseUrl}/api/restart`, { method: 'POST' });
    console.log(`[video] go2rtc reloaded with ${cameras.length} camera(s)`);
  } catch {
    console.log('[video] wrote go2rtc.yaml; start/restart go2rtc to apply');
  }
}
