import { writeFileSync } from 'node:fs';
import { exec } from 'node:child_process';
import type { CameraCfg } from '@yonderrc/protocol';

/**
 * Turns the graphical camera list into a go2rtc.yaml and reloads go2rtc — so the
 * user configures cameras (type, resolution, fps, bitrate) in the setup UI, not
 * by hand-editing a config file. Each camera becomes one selectable stream.
 *
 * The H.264 encoder is auto-detected so it works everywhere: libx264 (full
 * ffmpeg), libopenh264 (Fedora's patent-free ffmpeg-free), or a hardware encoder
 * on the Pi (h264_v4l2m2m) — no RPM Fusion required.
 */

/** Detect the best available H.264 encoder from the local ffmpeg. */
export function detectH264Encoder(): Promise<string> {
  return new Promise((resolve) => {
    exec('ffmpeg -hide_banner -encoders', { timeout: 8000 }, (_err, stdout) => {
      const out = stdout || '';
      // Prefer quality/latency: x264, then Cisco openh264, then Pi hardware.
      const prefer = ['libx264', 'libopenh264', 'h264_v4l2m2m', 'h264_omx', 'h264_nvenc'];
      for (const e of prefer) if (out.includes(e)) return resolve(e);
      resolve('libx264'); // last resort; preflight will have warned
    });
  });
}

/** Encoder-specific ffmpeg output args (libx264 presets don't apply elsewhere). */
function encoderArgs(encoder: string, fps: number, bitrateKbps?: number): string {
  const br = bitrateKbps && bitrateKbps > 0 ? bitrateKbps : null;
  if (encoder === 'libx264') {
    return (
      `-c:v libx264 -preset ultrafast -tune zerolatency -pix_fmt yuv420p -g ${fps}` +
      (br ? ` -b:v ${br}k -maxrate ${br}k -bufsize ${br * 2}k` : '')
    );
  }
  if (encoder === 'libopenh264') {
    // openh264 has no presets; needs an explicit bitrate.
    return `-c:v libopenh264 -profile:v constrained_baseline -pix_fmt yuv420p -g ${fps} -b:v ${br ?? 2000}k`;
  }
  if (encoder === 'h264_v4l2m2m' || encoder === 'h264_omx') {
    return `-c:v ${encoder} -pix_fmt yuv420p -g ${fps} -b:v ${br ?? 2000}k`;
  }
  return `-c:v ${encoder} -g ${fps}` + (br ? ` -b:v ${br}k` : '');
}

/** Round to an even number ≥ 2 (H.264 needs even dimensions). */
function even(n: number): number {
  return Math.max(2, Math.round(n / 2) * 2);
}

/**
 * Scale a camera's resolution/bitrate for a live quality level requested from the
 * ground. 'high' keeps the configured values; lower levels shrink dimensions and
 * cap bitrate so the picture stays fluid on a poor link.
 */
export function scaleCamera(cam: CameraCfg, quality: 'high' | 'medium' | 'low'): CameraCfg {
  if (quality === 'high') return cam;
  const factor = quality === 'medium' ? 0.66 : 0.5;
  const cap = quality === 'medium' ? 1200 : 600;
  return {
    ...cam,
    width: even(cam.width * factor),
    height: even(cam.height * factor),
    bitrateKbps: Math.min(cam.bitrateKbps ?? cap, cap),
  };
}
export function cameraSource(cam: CameraCfg, encoder = 'libx264'): string {
  const { width: w, height: h, fps } = cam;
  const enc = encoderArgs(encoder, fps, cam.bitrateKbps);
  if (cam.type === 'sim') {
    return `exec:ffmpeg -re -f lavfi -i testsrc=size=${w}x${h}:rate=${fps} ${enc} -f rtsp {output}`;
  }
  if (cam.type === 'rpicam') {
    const br = cam.bitrateKbps ? ` --bitrate ${cam.bitrateKbps * 1000}` : '';
    return (
      `exec:libcamera-vid -t 0 --inline --nopreview --codec h264 ` +
      `--width ${w} --height ${h} --framerate ${fps} --intra ${fps}${br} -o - | ` +
      `ffmpeg -fflags nobuffer -i - -c copy -f rtsp {output}`
    );
  }
  // usb (V4L2): transcode to H.264 with the detected encoder.
  const dev = cam.device ?? '/dev/video0';
  return `exec:ffmpeg -f v4l2 -framerate ${fps} -video_size ${w}x${h} -i ${dev} ${enc} -f rtsp {output}`;
}

export function generateGo2rtcYaml(cameras: CameraCfg[], encoder = 'libx264'): string {
  const lines: string[] = [
    '# Generated by YonderRC from the graphical camera settings — do not edit by hand.',
    `# H.264 encoder: ${encoder}`,
    'api:',
    '  listen: ":1984"',
    '  origin: "*"',
    'rtsp:',
    '  listen: ":8554"',
    'webrtc:',
    '  listen: ":8555"',
    '  candidates:',
    '    - stun:8555',
    'streams:',
  ];
  if (cameras.length === 0) {
    lines.push('  {}');
  } else {
    for (const cam of cameras) {
      lines.push(`  ${cam.name}: ${JSON.stringify(cameraSource(cam, encoder))}`);
    }
  }
  return lines.join('\n') + '\n';
}

/** Write the config file and ask a running go2rtc to reload it. */
export async function applyCameras(
  cameras: CameraCfg[],
  configPath: string,
  videoBaseUrl: string | null,
  encoder = 'libx264',
): Promise<void> {
  writeFileSync(configPath, generateGo2rtcYaml(cameras, encoder));
  if (!videoBaseUrl) return;
  try {
    await fetch(`${videoBaseUrl}/api/restart`, { method: 'POST' });
    console.log(`[video] go2rtc reloaded with ${cameras.length} camera(s), encoder ${encoder}`);
  } catch {
    console.log('[video] wrote go2rtc.yaml; start/restart go2rtc to apply');
  }
}
