#!/usr/bin/env bash
# YonderRC vehicle provisioning for Raspberry Pi OS Lite (Bookworm).
# Flash Pi OS Lite, boot, copy this repo to /opt/yonderrc, then run:
#   sudo bash /opt/yonderrc/provisioning/install.sh
set -euo pipefail

REPO=/opt/yonderrc
echo "== YonderRC provisioning =="

echo "-- packages"
apt-get update
# wireguard-tools = wg / wg-quick for the WireGuard remote-access option (e.g. FritzBox).
# usb-modeswitch = flips "Zero-CD" LTE dongles from storage mode into modem mode so
# ModemManager can see them (many Huawei/ZTE sticks need this).
# i2c-tools = i2cdetect for the setup page's "Detect hardware" probe.
# gpsd = optional GPS daemon (easiest path for USB GPS dongles).
apt-get install -y curl git ffmpeg network-manager modemmanager wireguard-tools usb-modeswitch i2c-tools gpsd

echo "-- Node.js 22"
if ! command -v node >/dev/null || [ "$(node -v | cut -c2-3)" -lt 20 ]; then
  curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
  apt-get install -y nodejs
fi

echo "-- Tailscale"
if ! command -v tailscale >/dev/null; then
  curl -fsSL https://tailscale.com/install.sh | sh
fi

echo "-- ZeroTier (optional remote-access method)"
if ! command -v zerotier-cli >/dev/null; then
  curl -fsSL https://install.zerotier.com | bash || echo "   (ZeroTier install skipped/failed — only needed if you pick ZeroTier)"
fi

echo "-- go2rtc"
if [ ! -x /usr/local/bin/go2rtc ]; then
  ARCH=$(dpkg --print-architecture) # arm64 / armhf
  case "$ARCH" in
    arm64) GOARCH=arm64 ;;
    armhf) GOARCH=armv7 ;;
    *) GOARCH=amd64 ;;
  esac
  curl -fsSL -o /usr/local/bin/go2rtc \
    "https://github.com/AlexxIT/go2rtc/releases/latest/download/go2rtc_linux_${GOARCH}"
  chmod +x /usr/local/bin/go2rtc
fi

echo "-- npm install (sim by default; hardware driver deps are optional)"
cd "$REPO"
# --omit=optional keeps the native hardware drivers (i2c-bus/pigpio/serialport) out of a
# plain sim install — see HARDWARE.md 3.3. But the flag is *global*: it also drops the
# platform binaries that rollup and esbuild ship as their own optionalDependencies, and
# the ground build then dies with "Cannot find module @rollup/rollup-linux-arm64-gnu".
npm install --omit=optional
# ...so install the ground workspace once more with optional deps allowed. That adds only
# @rollup/rollup-<arch> and @esbuild/<arch> (incl. vite's nested esbuild) — the vehicle's
# hardware drivers stay out because that workspace is not selected here.
npm install --include-workspace-root -w @yonderrc/ground

# Native driver modules the operator installed from the setup UI (Setup > Vehicle
# configuration > Native driver modules) are optionalDependencies too, so pass 1
# just pruned them. Put back exactly the ones this vehicle recorded — an update
# must not silently turn a configured vehicle back into a simulator.
CONFIG="${YRC_CONFIG:-$REPO/yonderrc-config.json}"
if [ -f "$CONFIG" ] && command -v python3 >/dev/null 2>&1; then
  DEPS=$(python3 - "$CONFIG" <<'PY'
import json, sys
ALLOWED = {'i2c-bus', 'pigpio', 'serialport'}   # mirrors hwDeps.ts
try:
    with open(sys.argv[1]) as f:
        deps = (json.load(f) or {}).get('hardwareDeps') or []
except Exception:
    deps = []
print(' '.join(sorted(d for d in deps if d in ALLOWED)))
PY
) || DEPS=""
  for dep in $DEPS; do
    echo "-- restoring native driver module: $dep"
    npm install "$dep" -w @yonderrc/vehicle ||
      echo "   ($dep failed to build — reinstall it in Setup > Vehicle configuration, it shows why)"
  done
fi

echo "-- build the ground control app (so a phone can fly/configure via the Pi)"
if ! npm run build -w @yonderrc/ground; then
  echo "   build failed — retrying once with a full install (incl. all optional deps)"
  npm install
  npm run build -w @yonderrc/ground
fi

echo "-- hardware access groups (I2C / GPIO / serial)"
usermod -aG i2c,gpio,dialout "${SUDO_USER:-pi}" || true
# Enable I2C + UART on the Pi if raspi-config is present:
if command -v raspi-config >/dev/null; then
  raspi-config nonint do_i2c 0 || true
  raspi-config nonint do_serial_hw 0 || true
fi

echo "-- runtime state directory (generated video config lives outside the checkout)"
# go2rtc's config is generated by the vehicle from the camera settings. It used to be
# written into docker/go2rtc.yaml inside the git checkout, which left every running
# vehicle with local modifications and blocked `git pull --ff-only` — including the
# update button in the setup page. Move it once, seed it from whatever is there now so
# go2rtc keeps its streams, and restore the checkout.
install -d -m 0755 /var/lib/yonderrc
if [ ! -f /var/lib/yonderrc/go2rtc.yaml ] && [ -f "$REPO/docker/go2rtc.yaml" ]; then
  cp "$REPO/docker/go2rtc.yaml" /var/lib/yonderrc/go2rtc.yaml
  echo "   (migrated the existing go2rtc config to /var/lib/yonderrc/)"
fi
if [ -d "$REPO/.git" ]; then
  git -c safe.directory="$REPO" -C "$REPO" checkout -- docker/go2rtc.yaml 2>/dev/null || true
fi

echo "-- systemd services"
cp "$REPO/provisioning/systemd/"*.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable --now go2rtc.service yonderrc-vehicle.service
# The onboarding hotspot is a oneshot fallback (it exits right away when the Pi already
# has a network). Never let it abort provisioning — the vehicle service is what matters.
systemctl enable --now yonderrc-onboard.service ||
  echo "   (onboard hotspot service did not start — check: journalctl -u yonderrc-onboard)"

echo
echo "== Done =="
echo "Setup UI:   http://<pi-ip>:8080/setup"
echo "If the Pi has no network, it starts an OPEN WiFi hotspot 'YonderRC-setup'"
echo "— join it; the captive portal opens http://192.168.4.1:8080/setup"
echo "There, Setup > WiFi scans and joins your network (and sets a hotspot password)."
